
os:
    - Visual Studio 2019

cache:
    - '%LOCALAPPDATA%\pip\Cache'

# fetch repository as zip archive
shallow_clone: true

environment:
    global:
        WIN_SDK_ROOT: "C:\\Program Files\\Microsoft SDKs\\Windows"
        VENV_BUILD_DIR: "venv_build"
        VENV_TEST_DIR: "venv_test"

    matrix:
        # Python 3.12
        - PYTHON_DIR: "C:\\Python312-x64"

branches:
    only:
        - master

install:
    # Add Python to PATH
    - "SET PATH=%PYTHON_DIR%;%PYTHON_DIR%\\Scripts;%PATH%"

    # Upgrade distribution modules
    - "pip install --upgrade setuptools"
    - "python -m pip install --upgrade pip"

    # Install virtualenv
    - "pip install virtualenv"
    - "virtualenv --version"

build_script:
    # Create build virtualenv
    - "virtualenv --clear %VENV_BUILD_DIR%"
    - "%VENV_BUILD_DIR%\\Scripts\\activate.bat"

    # Install build dependencies
    - "pip install --upgrade build"
    - "pip install --upgrade setuptools"
    - "pip install --upgrade wheel"
    # --no-isolation complains about oldest-supported-numpy not being installed
    - "pip install oldest-supported-numpy"
    #- "pip install --upgrade numpy"
    - "pip install numpy==1.26.4"
    - "pip install --upgrade cython"

    # Print Python info
    - "python ci\\info_platform.py"
    - "pip freeze"

    # Build
    - "python -m build --wheel"
    - ps: "ls dist"

    # Leave build virtualenv
    - "%VENV_BUILD_DIR%\\Scripts\\deactivate.bat"
    - "rmdir %VENV_BUILD_DIR% /s /q"

test_script:
    # Create test virtualenv
    - "virtualenv --clear %VENV_TEST_DIR%"
    - "%VENV_TEST_DIR%\\Scripts\\activate.bat"

    # Install the generated wheel package to test it
    - "pip install silx"
    - "pip install PyQt5"
    - "FOR %%F IN (dist\\PyMca5*.*) DO (
        pip install --pre %%F
      )"

    # Print Python info
    - "python ci\\info_platform.py"
    - "pip freeze"

    # Run the tests
    - "cd .."
    - "python -m PyMca5.tests.TestAll"

    # Leave test virtualenv
    - "pymca\\%VENV_TEST_DIR%\\Scripts\\deactivate.bat"
    - "rmdir pymca\\%VENV_TEST_DIR% /s /q"

artifacts:
    # Archive the generated wheel package in the ci.appveyor.com build report.
    - path: dist\*
